import { Customer, Product, InventoryItem, PriceEntry, Order, DeliverySlot, DeliveryRoute } from "@/types";

export const DEMO_COMPANY = {
  id: "dist-001",
  name: "JD Distribuidora y Gourmet Ahumados",
  shortName: "JD Distribuidora & Gourmet",
  tagline: "Proveedor directo de cortes de cerdo crudo y línea gourmet ahumados para famas, asaderos y restaurantes",
  phone: "+57 313 392 3080",
  whatsapp: "+57 320 494 8435",
  address: "Central de Carnes, Bodega Frigorífica JD, Bogotá D.C.",
  sanitaryRegistry: "Certificación Sanitaria INVIMA No. DESP-JD-9821",
};

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "cust-carlos",
    companyId: "dist-001",
    businessName: "Salsamentaria Carlos",
    contactName: "Carlos Rodríguez",
    nit: "900.542.118-4",
    phone: "312 456 7890",
    email: "carlos@salsamentariacarlos.com",
    address: "Carrera 45 # 68-22, Barrio Galerías",
    city: "Bogotá D.C.",
    zone: "Zona Centro & Chapinero (Galerías)",
    lat: 4.6525,
    lng: -74.0720,
    priceListId: "list-famas-a",
    assignedPriceListName: "Tarifa Institucional JD - Nivel A (Famas & Salsamentarias)",
    status: "active",
    paymentTerms: "Transferencia Bancaria / Crédito 15 días",
    minOrderAmount: 300000,
    deliveryDays: "Lunes a Sábado (Ruta de frío JD 0°C a 4°C)",
  },
  {
    id: "cust-pedro",
    companyId: "dist-001",
    businessName: "Fama y Carnicería El Roble",
    contactName: "Pedro Gómez",
    nit: "800.123.456-7",
    phone: "315 889 1234",
    email: "pedro@carniceriaelroble.com",
    address: "Calle 140 # 15-32, Cedritos",
    city: "Bogotá D.C.",
    zone: "Zona Norte (Cedritos - Usaquén)",
    lat: 4.7215,
    lng: -74.0320,
    priceListId: "list-famas-a",
    assignedPriceListName: "Tarifa Institucional JD - Nivel A (Famas & Salsamentarias)",
    status: "active",
    paymentTerms: "Contado contra entrega / Transferencia",
    minOrderAmount: 300000,
    deliveryDays: "Lunes a Sábado",
  },
  {
    id: "cust-asadero",
    companyId: "dist-001",
    businessName: "Asadero & Piqueteadero Don Jorge",
    contactName: "Jorge Beltrán",
    nit: "830.492.111-2",
    phone: "310 777 9988",
    email: "asaderojorge@gmail.com",
    address: "Avenida Esperanza # 75-40, Fontibón",
    city: "Bogotá D.C.",
    zone: "Zona Occidente (Fontibón - Modelia)",
    lat: 4.6750,
    lng: -74.1380,
    priceListId: "list-famas-a",
    assignedPriceListName: "Tarifa Restaurantes & Asaderos",
    status: "active",
    paymentTerms: "Transferencia Bancaria / Crédito 8 días",
    minOrderAmount: 300000,
    deliveryDays: "Lunes a Sábado",
  },
  {
    id: "cust-restaurante",
    companyId: "dist-001",
    businessName: "Restaurante Parrilla y Leño",
    contactName: "Marcela Henao",
    nit: "901.884.220-1",
    phone: "321 654 9870",
    email: "marcela@parrillayleno.com",
    address: "Calle 85 # 12-18, Zona Rosa",
    city: "Bogotá D.C.",
    zone: "Zona Norte (Zona Rosa - Chico)",
    lat: 4.6680,
    lng: -74.0550,
    priceListId: "list-famas-a",
    assignedPriceListName: "Tarifa Gourmet Horeca",
    status: "active",
    paymentTerms: "Crédito 30 días",
    minOrderAmount: 350000,
    deliveryDays: "Lunes a Sábado",
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // --- LÍNEA 1: JD DISTRIBUIDORA (CORTES CRUDOS FRESCOS) ---
  {
    id: "prod-bondiola",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-BON-01",
    name: "Bondiola de cerdo fresca",
    cutType: "Corte marmoleado crudo del cuello",
    presentation: "Pieza entera fresca al vacío / en canastilla",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Corte selecto del cuello del cerdo con extraordinario marmoleo intramuscular. Jugosidad y terneza garantizada para asados, hornos y porcionado.",
    category: "cortes_magros",
    image: "/images/products/bondiola.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 5,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-lomo",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-LOM-02",
    name: "Lomo / Cañón de cerdo extra magro",
    cutType: "Corte 100% magro crudo sin hueso",
    presentation: "Cañón entero limpio libre de grasa dorsal",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Lomo fino de cerdo crudo, corte magro de alta terneza. Estándar de calidad JD para porcionado en medallones, escalopes y milanesas.",
    category: "cortes_magros",
    image: "/images/products/lomo.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 5,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-solomito",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-SOL-03",
    name: "Solomito / Lomito fino de cerdo",
    cutType: "Corte premium crudo extra suave",
    presentation: "Pieza entera envasada al fresco",
    temperature: "Refrigerado 0°C a 4°C",
    description: "El corte más tierno y magro de la canal porcina. Pieza cilíndrica uniforme sin tejido conectivo para alta cocina y parrilladas.",
    category: "cortes_magros",
    image: "/images/products/solomito.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 2,
    active: true,
    isFrequent: false,
  },
  {
    id: "prod-costilla-sanluis",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-CST-04",
    name: "Costilla de cerdo San Luis (St. Louis Cut Cruda)",
    cutType: "Corte con hueso crudo parrillero",
    presentation: "Plancha rectangular de costillar carnudo",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Costillar crudo carnudo con corte recto uniforme sin puntas de cartílago. Corte insignia para asaderos, BBQ y restaurantes.",
    category: "cortes_con_hueso",
    image: "/images/products/costilla-sanluis.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 2,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-costilla-babyback",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-CST-05",
    name: "Costilla Baby Back de cerdo cruda",
    cutType: "Costillar tierno curvo del lomo",
    presentation: "Tiras individuales seleccionadas",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Costillitas tiernas provenientes de la parte superior del costillar cercano al lomo. Rápida cocción y máxima suavidad cárnica.",
    category: "cortes_con_hueso",
    image: "/images/products/costilla-babyback.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 2,
    active: true,
    isFrequent: false,
  },
  {
    id: "prod-panceta",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-PAN-06",
    name: "Panceta de cerdo fresca en plancha",
    cutType: "Corte ventral crudo equilibrado",
    presentation: "Bloque rectangular crudo con piel",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Panceta fresca cruda con capas simétricas de carne magra y grasa firme. Perfecta para confitar, hornear a baja temperatura o cortes gourmet.",
    category: "tocinos_grasas",
    image: "/images/products/panceta.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 5,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-tocino-barriguero",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-TOC-07",
    name: "Tocino barriguero crudo con piel (Para Chicharrón)",
    cutType: "Tocino crudo con piel marcada",
    presentation: "Tiras o planchas frescas listas para corte",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Tocino de primera calidad con piel limpia y flexible, ideal para chicharrón crocante de 100 puntos en asaderos, piqueteaderos y famas.",
    category: "tocinos_grasas",
    image: "/images/products/tocino-barriguero.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 5,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-pernil",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-PER-08",
    name: "Pernil de cerdo crudo (Pierna entera / desposte)",
    cutType: "Corte magro crudo con hueso / desposte",
    presentation: "Pierna entera fresca o en posta despostada",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Pierna trasera fresca de cerdo de granja tecnificada, carne magra cruda para asados en bloque, lechonerías, porcionado en carnicería o curados.",
    category: "cortes_magros",
    image: "/images/products/pernil.jpg",
    unit: "kg",
    minimumQuantity: 10,
    quantityStep: 5,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-brazo",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-BRZ-09",
    name: "Brazo / Paleta de cerdo cruda",
    cutType: "Corte crudo de paleta delantera",
    presentation: "Pieza entera fresca sin cuero",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Paleta delantera fresca de cerdo, tejido cárnico jugoso y suave, el insumo predilecto para salsamentarias, desmechados y hornos.",
    category: "cortes_magros",
    image: "/images/products/brazo.jpg",
    unit: "kg",
    minimumQuantity: 10,
    quantityStep: 5,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-chuleta",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-CHU-10",
    name: "Chuleta de cerdo fresca con hueso",
    cutType: "Corte con hueso crudo de lomo",
    presentation: "Chuletón en bloque fresco o porcionado",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Chuletón fresco de lomo con costilla y borde perimetral de grasa para máxima jugosidad a la plancha o carbón.",
    category: "cortes_con_hueso",
    image: "/images/products/chuleta.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 5,
    active: true,
    isFrequent: false,
  },
  {
    id: "prod-codillo",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-COD-11",
    name: "Codillo de cerdo crudo fresco",
    cutType: "Corte de articulación crudo con piel y hueso",
    presentation: "Piezas individuales limpias",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Corte tradicional ubicado entre la pierna y la manita, abundante en colágeno y carne melosa para horneados lentos y gastronomía gourmet.",
    category: "cortes_con_hueso",
    image: "/images/products/codillo.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 2,
    active: true,
    isFrequent: false,
  },
  {
    id: "prod-papada",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-PAP-12",
    name: "Papada de cerdo cruda fresca",
    cutType: "Grasa firme cruda para salsamentaria",
    presentation: "Pieza entera cruda limpia",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Grasa firme y carne magra con alto punto de fusión para elaboración de chorizos de alta calidad, guanciale y embutidos en salsamentaria.",
    category: "tocinos_grasas",
    image: "/images/products/papada.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 5,
    active: true,
    isFrequent: false,
  },
  {
    id: "prod-espinazo",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    sku: "JD-ESP-13",
    name: "Espinazo carnudo de cerdo crudo",
    cutType: "Corte con hueso vertebral crudo",
    presentation: "Hueso vertebral fresco con alta carne adherida",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Columna vertebral fresca con abundante carne para sancochos, caldos de fonda y venta popular en carnicerías.",
    category: "cortes_con_hueso",
    image: "/images/products/espinazo.jpg",
    unit: "kg",
    minimumQuantity: 10,
    quantityStep: 5,
    active: true,
    isFrequent: false,
  },

  // --- LÍNEA 2: GOURMET AHUMADOS (COSTILLAS Y CHULETAS AHUMADAS AL LEÑO) ---
  {
    id: "prod-costilla-ahumada",
    companyId: "dist-001",
    brand: "gourmet_ahumados",
    sku: "GA-CST-01",
    name: "Costilla de Cerdo Ahumada Tradicional Gourmet (St. Louis)",
    cutType: "Ahumado artesanal al leño de roble",
    presentation: "Costillar entero ahumado al vacío institucional",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Costillar St. Louis marinado con salmuera de especias finas y ahumado lentamente durante 6 horas con leña de roble. Tierna, jugosa y lista para dorar en asaderos, restaurantes y parrilladas.",
    category: "ahumados_costillas",
    image: "/images/products/costilla-ahumada.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 2,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-costilla-babyback-ahumada",
    companyId: "dist-001",
    brand: "gourmet_ahumados",
    sku: "GA-CST-02",
    name: "Costilla Baby Back Ahumada Gourmet al Leño",
    cutType: "Ahumado premium de costilla tierna",
    presentation: "Racks enteros ahumados al vacío",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Costillitas Baby Back ahumadas con notas aromáticas de humo natural y caramelo suave. Máxima suavidad cárnica, el producto estrella para cartas gastronómicas y eventos.",
    category: "ahumados_costillas",
    image: "/images/products/costilla-ahumada.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 2,
    active: true,
    isFrequent: true,
  },
  {
    id: "prod-chuleta-ahumada",
    companyId: "dist-001",
    brand: "gourmet_ahumados",
    sku: "GA-CHU-03",
    name: "Chuleta de Cerdo Ahumada Tradicional Gourmet",
    cutType: "Chuletón de lomo marinado y ahumado",
    presentation: "Chulatas gruesas con hueso empacadas al vacío",
    temperature: "Refrigerado 0°C a 4°C",
    description: "Corte de lomo con costilla curado y ahumado en caliente con maderas nobles. Extra jugosa, color caoba dorado y sabor ahumado profundo para salsamentarias, piqueteaderos y restaurantes.",
    category: "ahumados_chuletas",
    image: "/images/products/chuleta-ahumada.jpg",
    unit: "kg",
    minimumQuantity: 5,
    quantityStep: 5,
    active: true,
    isFrequent: true,
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  // Crudos JD
  { productId: "prod-bondiola", companyId: "dist-001", physicalQuantity: 50, reservedQuantity: 10, availableQuantity: 40, futureQuantity: 100, nextAvailabilityDate: "Jueves 27 de agosto", canReserveFuture: true },
  { productId: "prod-lomo", companyId: "dist-001", physicalQuantity: 40, reservedQuantity: 10, availableQuantity: 30, futureQuantity: 80, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-solomito", companyId: "dist-001", physicalQuantity: 25, reservedQuantity: 5, availableQuantity: 20, futureQuantity: 40, nextAvailabilityDate: "Jueves 27 de agosto", canReserveFuture: true },
  { productId: "prod-costilla-sanluis", companyId: "dist-001", physicalQuantity: 20, reservedQuantity: 8, availableQuantity: 12, futureQuantity: 120, nextAvailabilityDate: "Jueves 27 de agosto", canReserveFuture: true },
  { productId: "prod-costilla-babyback", companyId: "dist-001", physicalQuantity: 30, reservedQuantity: 5, availableQuantity: 25, futureQuantity: 60, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-panceta", companyId: "dist-001", physicalQuantity: 35, reservedQuantity: 5, availableQuantity: 30, futureQuantity: 70, nextAvailabilityDate: "Jueves 27 de agosto", canReserveFuture: true },
  { productId: "prod-tocino-barriguero", companyId: "dist-001", physicalQuantity: 0, reservedQuantity: 0, availableQuantity: 0, futureQuantity: 150, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-pernil", companyId: "dist-001", physicalQuantity: 100, reservedQuantity: 20, availableQuantity: 80, futureQuantity: 200, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-brazo", companyId: "dist-001", physicalQuantity: 60, reservedQuantity: 15, availableQuantity: 45, futureQuantity: 90, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-chuleta", companyId: "dist-001", physicalQuantity: 30, reservedQuantity: 5, availableQuantity: 25, futureQuantity: 50, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-codillo", companyId: "dist-001", physicalQuantity: 20, reservedQuantity: 0, availableQuantity: 20, futureQuantity: 40, nextAvailabilityDate: "Sábado 29 de agosto", canReserveFuture: true },
  { productId: "prod-papada", companyId: "dist-001", physicalQuantity: 30, reservedQuantity: 5, availableQuantity: 25, futureQuantity: 40, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-espinazo", companyId: "dist-001", physicalQuantity: 50, reservedQuantity: 10, availableQuantity: 40, futureQuantity: 80, nextAvailabilityDate: "Jueves 27 de agosto", canReserveFuture: true },

  // Ahumados Gourmet
  { productId: "prod-costilla-ahumada", companyId: "dist-001", physicalQuantity: 60, reservedQuantity: 15, availableQuantity: 45, futureQuantity: 150, nextAvailabilityDate: "Jueves 27 de agosto", canReserveFuture: true },
  { productId: "prod-costilla-babyback-ahumada", companyId: "dist-001", physicalQuantity: 40, reservedQuantity: 10, availableQuantity: 30, futureQuantity: 80, nextAvailabilityDate: "Viernes 28 de agosto", canReserveFuture: true },
  { productId: "prod-chuleta-ahumada", companyId: "dist-001", physicalQuantity: 50, reservedQuantity: 10, availableQuantity: 40, futureQuantity: 120, nextAvailabilityDate: "Jueves 27 de agosto", canReserveFuture: true },
];

export const INITIAL_PRICES: PriceEntry[] = [
  // Crudos JD
  { priceListId: "list-famas-a", productId: "prod-bondiola", pricePerUnit: 23000 },
  { priceListId: "list-famas-a", productId: "prod-lomo", pricePerUnit: 22000 },
  { priceListId: "list-famas-a", productId: "prod-solomito", pricePerUnit: 25000 },
  { priceListId: "list-famas-a", productId: "prod-costilla-sanluis", pricePerUnit: 20000 },
  { priceListId: "list-famas-a", productId: "prod-costilla-babyback", pricePerUnit: 22500 },
  { priceListId: "list-famas-a", productId: "prod-panceta", pricePerUnit: 22000 },
  { priceListId: "list-famas-a", productId: "prod-tocino-barriguero", pricePerUnit: 21500 },
  { priceListId: "list-famas-a", productId: "prod-pernil", pricePerUnit: 18500 },
  { priceListId: "list-famas-a", productId: "prod-brazo", pricePerUnit: 19000 },
  { priceListId: "list-famas-a", productId: "prod-chuleta", pricePerUnit: 20500 },
  { priceListId: "list-famas-a", productId: "prod-codillo", pricePerUnit: 15500 },
  { priceListId: "list-famas-a", productId: "prod-papada", pricePerUnit: 16500 },
  { priceListId: "list-famas-a", productId: "prod-espinazo", pricePerUnit: 12000 },

  // Ahumados Gourmet
  { priceListId: "list-famas-a", productId: "prod-costilla-ahumada", pricePerUnit: 26000 },
  { priceListId: "list-famas-a", productId: "prod-costilla-babyback-ahumada", pricePerUnit: 28500 },
  { priceListId: "list-famas-a", productId: "prod-chuleta-ahumada", pricePerUnit: 24500 },
];

export const INITIAL_ORDERS: Order[] = [
  // --- RUTA 1: CARLOS PÉREZ (5 PARADAS REALISTAS EN CADENA DE FRÍO) ---
  {
    id: "ord-10454",
    orderNumber: "#10454",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    customerId: "cust-pedro",
    customerName: "Fama & Carnicería El Roble",
    items: [
      {
        productId: "prod-bondiola",
        sku: "JD-BON-01",
        productName: "Bondiola de cerdo fresca",
        unit: "kg",
        quantity: 20,
        unitPrice: 23000,
        subtotal: 460000,
      },
      {
        productId: "prod-lomo",
        sku: "JD-LOM-02",
        productName: "Lomo / Cañón de cerdo extra magro",
        unit: "kg",
        quantity: 15,
        unitPrice: 22000,
        subtotal: 330000,
      },
    ],
    subtotal: 790000,
    total: 790000,
    deliveryDate: "Jueves 27 de agosto",
    deliveryAddress: "Calle 140 # 15-32, Barrio Cedritos, Bogotá",
    zone: "Zona Norte (Cedritos - Usaquén)",
    lat: 4.7215,
    lng: -74.0320,
    routeId: "route-norte-01",
    routeName: "Ruta 1 - Zona Norte (Usaquén - Suba)",
    stopOrder: 1,
    driverName: "Carlos Pérez",
    driverPhone: "+57 314 200 1122",
    sealNumber: "PREC-JD-9012",
    notes: "Entregar en la carnicería a primera hora (07:30 AM).",
    status: "delivered",
    paymentMethod: "efectivo",
    createdAt: "2026-08-26T07:45:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "ord-10455",
    orderNumber: "#10455",
    companyId: "dist-001",
    brand: "gourmet_ahumados",
    customerId: "cust-asadero-jorge",
    customerName: "Restaurante & Asadero Don Jorge",
    items: [
      {
        productId: "prod-costilla-ahumada",
        sku: "GA-CST-01",
        productName: "Costilla de Cerdo Ahumada Tradicional Gourmet",
        unit: "kg",
        quantity: 25,
        unitPrice: 26000,
        subtotal: 650000,
      },
      {
        productId: "prod-chuleta-ahumada",
        sku: "GA-CHU-03",
        productName: "Chuleta de Cerdo Ahumada Tradicional Gourmet",
        unit: "kg",
        quantity: 20,
        unitPrice: 24500,
        subtotal: 490000,
      },
      {
        productId: "prod-panceta",
        sku: "JD-PAN-06",
        productName: "Panceta de cerdo fresca en plancha",
        unit: "kg",
        quantity: 10,
        unitPrice: 22000,
        subtotal: 220000,
      },
    ],
    subtotal: 1360000,
    total: 1360000,
    deliveryDate: "Jueves 27 de agosto",
    deliveryAddress: "Carrera 19 # 106-45, Barrio Usaquén, Bogotá",
    zone: "Zona Norte (Usaquén)",
    lat: 4.6935,
    lng: -74.0510,
    routeId: "route-norte-01",
    routeName: "Ruta 1 - Zona Norte (Usaquén - Suba)",
    stopOrder: 2,
    driverName: "Carlos Pérez",
    driverPhone: "+57 314 200 1122",
    sealNumber: "PREC-JD-9013",
    notes: "Llamar al administrador 10 minutos antes de llegar.",
    status: "delivered",
    paymentMethod: "banco",
    createdAt: "2026-08-26T08:00:00Z",
    updatedAt: "2026-08-26T10:10:00Z",
  },
  {
    id: "ord-10456",
    orderNumber: "#10456",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    customerId: "cust-piqueteadero-80",
    customerName: "Piqueteadero & Fonda La 80",
    items: [
      {
        productId: "prod-tocino-barriguero",
        sku: "JD-TOC-07",
        productName: "Tocino barriguero crudo con piel (Para Chicharrón)",
        unit: "kg",
        quantity: 25,
        unitPrice: 21500,
        subtotal: 537500,
      },
      {
        productId: "prod-pernil",
        sku: "JD-PER-08",
        productName: "Pernil de cerdo crudo (Pierna entera)",
        unit: "kg",
        quantity: 25,
        unitPrice: 18500,
        subtotal: 462500,
      },
    ],
    subtotal: 1000000,
    total: 1000000,
    deliveryDate: "Jueves 27 de agosto",
    deliveryAddress: "Calle 80 # 58-12, Barrio Polo Club, Bogotá",
    zone: "Zona Norte (Polo Club / Calle 80)",
    lat: 4.6720,
    lng: -74.0710,
    routeId: "route-norte-01",
    routeName: "Ruta 1 - Zona Norte (Usaquén - Suba)",
    stopOrder: 3,
    driverName: "Carlos Pérez",
    driverPhone: "+57 314 200 1122",
    sealNumber: "PREC-JD-9014",
    notes: "Descargar en cuarto frío posterior del piqueteadero.",
    status: "delivered",
    paymentMethod: "credito",
    createdAt: "2026-08-26T08:15:00Z",
    updatedAt: "2026-08-26T10:15:00Z",
  },
  {
    id: "ord-10457",
    orderNumber: "#10457",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    customerId: "cust-cabana-suba",
    customerName: "Carnicería & Fama La Cabaña de Suba",
    items: [
      {
        productId: "prod-costilla-sanluis",
        sku: "JD-CST-04",
        productName: "Costilla de cerdo San Luis (St. Louis Cut Cruda)",
        unit: "kg",
        quantity: 20,
        unitPrice: 20000,
        subtotal: 400000,
      },
      {
        productId: "prod-brazo",
        sku: "JD-BRZ-09",
        productName: "Brazo / Paleta de cerdo cruda",
        unit: "kg",
        quantity: 20,
        unitPrice: 19000,
        subtotal: 380000,
      },
    ],
    subtotal: 780000,
    total: 780000,
    deliveryDate: "Jueves 27 de agosto",
    deliveryAddress: "Avenida Suba # 118-40, Barrio Suba Centro, Bogotá",
    zone: "Zona Norte (Suba Centro)",
    lat: 4.7080,
    lng: -74.0760,
    routeId: "route-norte-01",
    routeName: "Ruta 1 - Zona Norte (Usaquén - Suba)",
    stopOrder: 4,
    driverName: "Carlos Pérez",
    driverPhone: "+57 314 200 1122",
    sealNumber: "PREC-JD-9015",
    notes: "Recoger 2 canastillas vacías del turno anterior.",
    status: "dispatched",
    paymentMethod: "efectivo",
    createdAt: "2026-08-26T08:30:00Z",
    updatedAt: "2026-08-26T10:20:00Z",
  },
  {
    id: "ord-10458",
    orderNumber: "#10458",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    customerId: "cust-brasas-toberin",
    customerName: "Asadero Carnes & Brasas Toberín",
    items: [
      {
        productId: "prod-costilla-babyback",
        sku: "JD-CST-05",
        productName: "Costilla Baby Back de cerdo cruda",
        unit: "kg",
        quantity: 25,
        unitPrice: 22500,
        subtotal: 562500,
      },
      {
        productId: "prod-solomito",
        sku: "JD-SOL-03",
        productName: "Solomito / Lomito fino de cerdo",
        unit: "kg",
        quantity: 15,
        unitPrice: 25000,
        subtotal: 375000,
      },
      {
        productId: "prod-costilla-ahumada",
        sku: "GA-CST-01",
        productName: "Costilla de Cerdo Ahumada Tradicional Gourmet",
        unit: "kg",
        quantity: 20,
        unitPrice: 26000,
        subtotal: 520000,
      },
    ],
    subtotal: 1457500,
    total: 1457500,
    deliveryDate: "Jueves 27 de agosto",
    deliveryAddress: "Autopista Norte # 168-20, Barrio Toberín, Bogotá",
    zone: "Zona Norte (Toberín)",
    lat: 4.7480,
    lng: -74.0410,
    routeId: "route-norte-01",
    routeName: "Ruta 1 - Zona Norte (Usaquén - Suba)",
    stopOrder: 5,
    driverName: "Carlos Pérez",
    driverPhone: "+57 314 200 1122",
    sealNumber: "PREC-JD-9016",
    notes: "Punto final de la ruta norte antes de retornar a planta.",
    status: "dispatched",
    createdAt: "2026-08-26T08:45:00Z",
    updatedAt: "2026-08-26T10:25:00Z",
  },

  // --- RUTA 2: JUAN CAMILO MÉNDEZ (ZONA CENTRO) ---
  {
    id: "ord-10452",
    orderNumber: "#10452",
    companyId: "dist-001",
    brand: "jd_distribuidora",
    customerId: "cust-carlos",
    customerName: "Salsamentaria Carlos",
    items: [
      {
        productId: "prod-pernil",
        sku: "JD-PER-08",
        productName: "Pernil de cerdo crudo (Pierna entera)",
        unit: "kg",
        quantity: 30,
        unitPrice: 18500,
        subtotal: 555000,
      },
      {
        productId: "prod-costilla-sanluis",
        sku: "JD-CST-04",
        productName: "Costilla de cerdo San Luis",
        unit: "kg",
        quantity: 20,
        unitPrice: 20000,
        subtotal: 400000,
      },
      {
        productId: "prod-tocino-barriguero",
        sku: "JD-TOC-07",
        productName: "Tocino barriguero crudo con piel",
        unit: "kg",
        quantity: 10,
        unitPrice: 21500,
        subtotal: 215000,
      },
    ],
    subtotal: 1170000,
    total: 1170000,
    deliveryDate: "Jueves 27 de agosto",
    deliveryAddress: "Carrera 45 # 68-22, Barrio Galerías, Bogotá",
    zone: "Zona Centro & Chapinero (Galerías)",
    lat: 4.6525,
    lng: -74.0720,
    routeId: "route-centro-02",
    routeName: "Ruta 2 - Centro & Chapinero",
    stopOrder: 1,
    driverName: "Juan Camilo Méndez",
    driverPhone: "+57 318 555 4321",
    sealNumber: "PREC-JD-8849",
    notes: "Despachar en furgón refrigerado JD con precinto de desposte.",
    status: "preparing",
    createdAt: "2026-08-26T08:30:00Z",
    updatedAt: "2026-08-26T10:15:00Z",
  },

  // --- RUTA 3: ANDRÉS ROA (ZONA OCCIDENTE) ---
  {
    id: "ord-10453",
    orderNumber: "#10453",
    companyId: "dist-001",
    brand: "gourmet_ahumados",
    customerId: "cust-asadero",
    customerName: "Asadero & Piqueteadero Don Jorge",
    items: [
      {
        productId: "prod-costilla-ahumada",
        sku: "GA-CST-01",
        productName: "Costilla de Cerdo Ahumada Tradicional Gourmet",
        unit: "kg",
        quantity: 25,
        unitPrice: 26000,
        subtotal: 650000,
      },
      {
        productId: "prod-chuleta-ahumada",
        sku: "GA-CHU-03",
        productName: "Chuleta de Cerdo Ahumada Tradicional Gourmet",
        unit: "kg",
        quantity: 20,
        unitPrice: 24500,
        subtotal: 490000,
      },
    ],
    subtotal: 1140000,
    total: 1140000,
    deliveryDate: "Jueves 27 de agosto",
    deliveryAddress: "Avenida Esperanza # 75-40, Fontibón, Bogotá",
    zone: "Zona Occidente (Fontibón - Modelia)",
    lat: 4.6750,
    lng: -74.1380,
    routeId: "route-occidente-03",
    routeName: "Ruta 3 - Occidente & Fontibón",
    stopOrder: 1,
    driverName: "Andrés Roa",
    driverPhone: "+57 311 987 6543",
    sealNumber: "PREC-JD-7721",
    notes: "Empacado al vacío para asadero. Entregar antes de las 10am.",
    status: "confirmed",
    createdAt: "2026-08-26T09:15:00Z",
    updatedAt: "2026-08-26T09:30:00Z",
  },
];

export const INITIAL_ROUTES: DeliveryRoute[] = [
  {
    id: "route-norte-01",
    name: "Ruta 1 - Zona Norte (Usaquén - Suba - Cedritos)",
    zone: "Zona Norte",
    driverId: "drv-carlos",
    driverName: "Carlos Pérez",
    driverPhone: "+57 314 200 1122",
    vehiclePlate: "KLP-541 (Furgón Térmico 0°C a 4°C)",
    vehicleType: "furgon_frio",
    orderIds: ["ord-10454", "ord-10455", "ord-10456", "ord-10457", "ord-10458"],
    status: "in_transit",
    departureTime: "07:00 AM",
    date: "Jueves 27 de agosto",
    notes: "Ruta principal de 5 paradas: Cedritos -> Usaquén -> Polo Club -> Suba -> Toberín.",
  },
  {
    id: "route-centro-02",
    name: "Ruta 2 - Zona Centro & Chapinero (Galerías - Teusaquillo)",
    zone: "Zona Centro",
    driverId: "drv-juanc",
    driverName: "Juan Camilo Méndez",
    driverPhone: "+57 318 555 4321",
    vehiclePlate: "SZK-915 (Furgón Frigorífico Grande)",
    vehicleType: "furgon_frio",
    orderIds: ["ord-10452"],
    status: "in_transit",
    departureTime: "06:30 AM",
    date: "Jueves 27 de agosto",
    notes: "Ruta principal de salsamentarias y carnicerías centrales.",
  },
  {
    id: "route-occidente-03",
    name: "Ruta 3 - Zona Occidente & Fontibón (Modelia - Engativá)",
    zone: "Zona Occidente",
    driverId: "drv-andres",
    driverName: "Andrés Roa",
    driverPhone: "+57 311 987 6543",
    vehiclePlate: "UFR-210 (Furgón Mediano)",
    vehicleType: "furgon_frio",
    orderIds: ["ord-10453"],
    status: "planned",
    departureTime: "07:30 AM",
    date: "Jueves 27 de agosto",
    notes: "Despacho de costillas y chuletas ahumadas para asaderos.",
  },
];

export const INITIAL_DELIVERY_SLOTS: DeliverySlot[] = [
  {
    id: "slot-today",
    dateKey: "2026-08-26",
    dayName: "HOY",
    dateFormatted: "Miércoles 26 de agosto",
    status: "unavailable",
    statusText: "No disponible (Ruta cerrada)",
    note: "Cierre de pedidos del turno: 6:00 a.m.",
  },
  {
    id: "slot-tomorrow",
    dateKey: "2026-08-27",
    dayName: "JUEVES 27",
    dateFormatted: "Jueves 27 de agosto",
    status: "available",
    statusText: "Disponible",
    note: "Despacho en furgón refrigerado JD (0°C a 4°C)",
  },
  {
    id: "slot-friday",
    dateKey: "2026-08-28",
    dayName: "VIERNES 28",
    dateFormatted: "Viernes 28 de agosto",
    status: "available",
    statusText: "Disponible",
    note: "Recepción de lote fresco de granja y ahumados",
  },
  {
    id: "slot-saturday",
    dateKey: "2026-08-29",
    dayName: "SÁBADO 29",
    dateFormatted: "Sábado 29 de agosto",
    status: "limited",
    statusText: "Cupo limitado",
    note: "Últimos cupos de ruta matutina",
  },
  {
    id: "slot-sunday",
    dateKey: "2026-08-30",
    dayName: "DOMINGO 30",
    dateFormatted: "Domingo 30 de agosto",
    status: "unavailable",
    statusText: "No disponible",
    note: "Planta de desposte cerrada",
  },
  {
    id: "slot-monday",
    dateKey: "2026-08-31",
    dayName: "LUNES 31",
    dateFormatted: "Lunes 31 de agosto",
    status: "available",
    statusText: "Disponible",
    note: "Primer turno semanal de beneficio y desposte",
  },
];
